/**
 * Autonomous Scanner - Proactively identifies work that needs to be done
 *
 * Runs when the agent is idle and:
 * 1. Checks for due cadences (daily standups, weekly preps, etc.)
 * 2. Reviews responsibilities needing attention
 * 3. Uses LLM to determine what tasks should be created
 */

import { query } from '@anthropic-ai/claude-agent-sdk';
import { ResponsibilityManager, Responsibility, Cadence } from '../memory/responsibilities.js';
import { TaskQueue } from './task-queue.js';
import { ContextStore } from '../memory/context-store.js';
import { GoalManager } from '../memory/goals.js';

export interface ScanResult {
  scannedAt: Date;
  dueCadences: Array<{ responsibility: Responsibility; cadence: Cadence }>;
  needingAttention: Responsibility[];
  tasksCreated: number;
  nextScanAt: Date;
}

export class AutonomousScanner {
  private responsibilityManager: ResponsibilityManager;
  private taskQueue: TaskQueue;
  private contextStore: ContextStore;
  private goalManager: GoalManager;

  private lastScanAt: Date | null = null;
  private scanIntervalMs: number;
  private model?: string;
  private cwd: string;

  constructor(params: {
    responsibilityManager: ResponsibilityManager;
    taskQueue: TaskQueue;
    contextStore: ContextStore;
    goalManager: GoalManager;
    scanIntervalMs?: number;
    model?: string;
    cwd?: string;
  }) {
    this.responsibilityManager = params.responsibilityManager;
    this.taskQueue = params.taskQueue;
    this.contextStore = params.contextStore;
    this.goalManager = params.goalManager;
    this.scanIntervalMs = params.scanIntervalMs ?? 30 * 60 * 1000; // 30 min default
    this.model = params.model;
    this.cwd = params.cwd ?? process.cwd();
  }

  /**
   * Check if it's time to scan
   */
  shouldScan(): boolean {
    if (!this.lastScanAt) return true;
    return Date.now() - this.lastScanAt.getTime() >= this.scanIntervalMs;
  }

  /**
   * Get time until next scan
   */
  getNextScanTime(): Date {
    if (!this.lastScanAt) return new Date();
    return new Date(this.lastScanAt.getTime() + this.scanIntervalMs);
  }

  /**
   * Run the autonomous scan
   */
  async scan(): Promise<ScanResult> {
    console.log('[SCAN] Starting autonomous scan...');
    this.lastScanAt = new Date();

    // 1. Get due cadences
    const dueCadences = this.responsibilityManager.getDueCadences();
    if (dueCadences.length > 0) {
      console.log(`[SCAN] Found ${dueCadences.length} due cadence(s)`);
    }

    // 2. Get responsibilities needing attention
    const needingAttention = this.responsibilityManager.getNeedingAttention(24);
    if (needingAttention.length > 0) {
      console.log(`[SCAN] Found ${needingAttention.length} responsibility(ies) needing attention`);
    }

    // 3. Get active goals without tasks
    const goalsWithoutTasks = this.goalManager.getActiveGoals().filter(
      (g) => g.taskIds.length === 0
    );

    // If nothing needs attention, skip LLM call
    if (dueCadences.length === 0 && needingAttention.length === 0 && goalsWithoutTasks.length === 0) {
      console.log('[SCAN] Nothing needs attention');
      return {
        scannedAt: this.lastScanAt,
        dueCadences: [],
        needingAttention: [],
        tasksCreated: 0,
        nextScanAt: this.getNextScanTime(),
      };
    }

    // 4. Build context for LLM
    const planningPrompt = this.buildPlanningPrompt(dueCadences, needingAttention, goalsWithoutTasks);

    // 5. Ask LLM what tasks to create
    let tasksCreated = 0;
    try {
      const tasks = await this.planTasks(planningPrompt);

      // 6. Create tasks
      for (const task of tasks) {
        console.log(`[SCAN] Creating task: ${task.title}`);
        const created = this.taskQueue.addTask({
          title: task.title,
          description: task.description,
          priority: task.priority ?? 'medium',
          parentGoalId: task.goalId,
          context: {
            responsibilityId: task.responsibilityId,
            cadenceId: task.cadenceId,
            autoGenerated: true,
            generatedAt: new Date().toISOString(),
          },
        });

        // Link to goal if applicable
        if (task.goalId) {
          this.goalManager.addTaskToGoal(task.goalId, created.id);
        }

        // Mark cadence as triggered
        if (task.responsibilityId && task.cadenceId) {
          this.responsibilityManager.triggerCadence(task.responsibilityId, task.cadenceId);
        }

        // Mark responsibility as attended
        if (task.responsibilityId) {
          this.responsibilityManager.markAttended(task.responsibilityId);
          this.responsibilityManager.addActivity(
            task.responsibilityId,
            'task_created',
            task.title,
            created.id
          );
        }

        tasksCreated++;
      }
    } catch (error) {
      console.error('[SCAN] Error planning tasks:', error);
    }

    console.log(`[SCAN] Complete. Created ${tasksCreated} task(s).`);

    return {
      scannedAt: this.lastScanAt,
      dueCadences,
      needingAttention,
      tasksCreated,
      nextScanAt: this.getNextScanTime(),
    };
  }

  /**
   * Build the prompt for the LLM planner
   */
  private buildPlanningPrompt(
    dueCadences: Array<{ responsibility: Responsibility; cadence: Cadence }>,
    needingAttention: Responsibility[],
    goalsWithoutTasks: Array<{ id: string; title: string; description: string }>
  ): string {
    const now = new Date();
    const dayOfWeek = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'][now.getDay()];

    let prompt = `# Autonomous Planning Session

Current time: ${now.toISOString()}
Day: ${dayOfWeek}

You are Deputy, an autonomous executive assistant. Review the following and determine what tasks should be created.

`;

    // Due cadences
    if (dueCadences.length > 0) {
      prompt += `## Due Cadences (scheduled activities that are now due)\n\n`;
      for (const { responsibility, cadence } of dueCadences) {
        prompt += `### ${cadence.name} (${responsibility.name})
- Domain: ${responsibility.domain}
- Phase: ${responsibility.phase ?? 'n/a'}
- Context: ${cadence.context ?? responsibility.description}
- People: ${responsibility.people.map((p) => p.name).join(', ') || 'none specified'}
- Channels: ${JSON.stringify(responsibility.channels)}

`;
      }
    }

    // Responsibilities needing attention
    if (needingAttention.length > 0) {
      prompt += `## Responsibilities Needing Attention (no activity in 24+ hours)\n\n`;
      for (const r of needingAttention) {
        prompt += `### ${r.name}
- Domain: ${r.domain}
- Phase: ${r.phase ?? 'n/a'}
- Description: ${r.description}
- Last attended: ${r.lastAttendedAt?.toISOString() ?? 'never'}
- Context: ${r.context.slice(-500) || 'none'}

`;
      }
    }

    // Goals without tasks
    if (goalsWithoutTasks.length > 0) {
      prompt += `## Goals Without Tasks (need decomposition)\n\n`;
      for (const g of goalsWithoutTasks) {
        prompt += `### ${g.title}
- Description: ${g.description}

`;
      }
    }

    // Context summary
    const contextSummary = this.contextStore.buildContextSummary();
    if (contextSummary) {
      prompt += `## Accumulated Context\n\n${contextSummary}\n\n`;
    }

    prompt += `## Instructions

Based on the above, create tasks that should be executed. For each task, provide:
- title: Clear, actionable title
- description: What needs to be done
- priority: low, medium, high, or critical
- responsibilityId: If related to a responsibility (use ID from above)
- cadenceId: If triggered by a cadence (use ID from above)
- goalId: If decomposing a goal (use ID from above)

Consider:
- What's the most important thing to do right now?
- What can be done autonomously vs what needs approval?
- Are there any time-sensitive items?
- For cadences, what specific actions are needed?

Respond with a JSON array of tasks. Example:
\`\`\`json
[
  {
    "title": "Prepare daily standup summary for Project X",
    "description": "Check Jira for updates, identify blockers, prepare summary for team",
    "priority": "high",
    "responsibilityId": "...",
    "cadenceId": "..."
  }
]
\`\`\`

If no tasks are needed, return an empty array: []
`;

    return prompt;
  }

  /**
   * Call LLM to plan tasks
   */
  private async planTasks(prompt: string): Promise<
    Array<{
      title: string;
      description: string;
      priority?: 'low' | 'medium' | 'high' | 'critical';
      responsibilityId?: string;
      cadenceId?: string;
      goalId?: string;
    }>
  > {
    let response = '';

    for await (const message of query({
      prompt,
      options: {
        systemPrompt: 'You are a planning assistant. Analyze the context and output a JSON array of tasks.',
        cwd: this.cwd,
        model: this.model,
        allowedTools: [], // No tools needed for planning
      },
    })) {
      if ('result' in message && message.result) {
        response = message.result;
      }
    }

    // Extract JSON from response
    const jsonMatch = response.match(/```json\s*([\s\S]*?)\s*```/) || response.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      console.log('[SCAN] No valid JSON in response');
      return [];
    }

    try {
      const json = jsonMatch[1] ?? jsonMatch[0];
      const tasks = JSON.parse(json);
      if (!Array.isArray(tasks)) return [];
      return tasks;
    } catch (e) {
      console.error('[SCAN] Failed to parse tasks JSON:', e);
      return [];
    }
  }

  /**
   * Force a scan regardless of interval
   */
  async forceScan(): Promise<ScanResult> {
    this.lastScanAt = null;
    return this.scan();
  }

  /**
   * Set scan interval
   */
  setScanInterval(ms: number): void {
    this.scanIntervalMs = ms;
  }
}
